---
- name: Resolve lab identity
  ansible.builtin.include_role:
    name: lab-user
    tasks_from: identity

- name: Create directory for student lab dockerfiles
  ansible.builtin.file:
    path: "{{ lab_dir }}"
    state: directory
    mode: "0755"

- name: Create directory for appdata
  ansible.builtin.file:
    path: /opt/appdata
    state: directory
    mode: "0775"

- name: Set Ownership on Appdata Directory
  ansible.builtin.file:
    path: /opt/appdata
    owner: "{{ lab_uid }}"
    group: "{{ lab_gid }}"
    recurse: true

- name: Set Ownership on Casdoor DB
  ansible.builtin.file:
    path: "{{ lab_dir }}/services/casdoor"
    owner: "{{ lab_uid }}"
    group: "{{ lab_gid }}"
    mode: "0777"
    recurse: true

- name: Set Ownership on prometheus directory
  ansible.builtin.file:
    path: "{{ lab_dir }}/services/prometheus"
    owner: "{{ lab_uid }}"
    group: "{{ lab_gid }}"
    mode: "0777"
    recurse: true


- name: Set Ownership on jupyterlab workspace 
  ansible.builtin.file:
    path: "{{ lab_dir }}/services/dockge/stacks/lab-tools-jupyter/workspace"
    owner: "{{ lab_uid }}"
    group: "{{ lab_gid }}"
    mode: "0775"
    recurse: true
