---
- name: Resolve lab identity
  ansible.builtin.import_tasks: identity.yaml

- name: Ensure the lab group exists
  ansible.builtin.group:
    name: "{{ lab_group }}"
    gid: "{{ lab_gid }}"
    state: present

- name: Ensure the lab user exists
  ansible.builtin.user:
    name: "{{ lab_user }}"
    uid: "{{ lab_uid }}"
    group: "{{ lab_group }}"
    state: present

- name: Ensure the user is part of the sudo group
  ansible.builtin.user:
    name: "{{ lab_user }}"
    groups: sudo
    append: true

- name: Ensure the user is part of the docker group
  ansible.builtin.user:
    name: "{{ lab_user }}"
    groups: docker
    append: true
